server:
  port: 8082

spring:
  application:
    name: enchanter-mall-order

  datasource:
    #url: jdbc:mysql://116.204.82.200:3306/gulimall_pms?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/gulimall_oms?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
